// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Napat1;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Napat1_Roo_Jpa_Entity {
    
    declare @type: Napat1: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Napat1.id;
    
    @Version
    @Column(name = "version")
    private Integer Napat1.version;
    
    public Long Napat1.getId() {
        return this.id;
    }
    
    public void Napat1.setId(Long id) {
        this.id = id;
    }
    
    public Integer Napat1.getVersion() {
        return this.version;
    }
    
    public void Napat1.setVersion(Integer version) {
        this.version = version;
    }
    
}
