// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Napat1;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Napat1_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Napat1.entityManager;
    
    public static final List<String> Napat1.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Napat1.entityManager() {
        EntityManager em = new Napat1().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Napat1.countNapat1s() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Napat1 o", Long.class).getSingleResult();
    }
    
    public static List<Napat1> Napat1.findAllNapat1s() {
        return entityManager().createQuery("SELECT o FROM Napat1 o", Napat1.class).getResultList();
    }
    
    public static List<Napat1> Napat1.findAllNapat1s(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Napat1 o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Napat1.class).getResultList();
    }
    
    public static Napat1 Napat1.findNapat1(Long id) {
        if (id == null) return null;
        return entityManager().find(Napat1.class, id);
    }
    
    public static List<Napat1> Napat1.findNapat1Entries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Napat1 o", Napat1.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Napat1> Napat1.findNapat1Entries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Napat1 o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Napat1.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Napat1.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Napat1.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Napat1 attached = Napat1.findNapat1(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Napat1.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Napat1.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Napat1 Napat1.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Napat1 merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
