// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Napat1;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Napat1_Roo_Configurable {
    
    declare @type: Napat1: @Configurable;
    
}
